### PR TITLE
Fixes #391 - check for vm placement policy feature support

### LINKED ISSUE #391: Placement policy creation should check the oVirt version
## Describe the bug

Placement policy requires at least oVirt 4.4.5. The placement policy setting should check the oVirt version.

### PR DESCRIPTION
**Pull request by engelmi**
## Please describe the change you are making

This PR fixes #391 by checking if the vm creation policy feature is supported by the current oVirt version. 

## Are you the owner of the code you are sending in, or do you have permission of the owner?

yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

yes

### CODE REVIEW

File: internal/ovirt/resource_ovirt_vm.go [hunk 1]
```diff
@@ -219,6 +218,11 @@ func (p *provider) vmCreate(
 		diags = f(data, params, diags)
 	}
 
+	diags = handleVMPlacementPolicy(client, data, params, diags)
+	if diags.HasError() {
```
Comment (engelmi) [inline internal/ovirt/resource_ovirt_vm.go:222]: Previously, `diags` was only used to append errors in the handle functions. I am not sure, if checking for an error and returning the `diags` is desired behavior. If not, I can easily remove it again.

File: internal/ovirt/resource_ovirt_vm.go [hunk 2]
```diff
@@ -377,7 +382,16 @@ func handleVMPlacementPolicy(
 		}
 		hasPlacementPolicy = true
 	}
+
 	if hasPlacementPolicy {
+		if isSupported, _ := client.SupportsFeature(ovirtclient.FeaturePlacementPolicy); !isSupported {
```
Comment (janosdebugs) [inline internal/ovirt/resource_ovirt_vm.go:387]: We must handle the error here as the call to oVirt can fail. That error must be logged.

**Review by janosdebugs — CHANGES_REQUESTED** [review]

File: internal/ovirt/resource_ovirt_vm.go [hunk 3]
```diff
@@ -219,6 +218,11 @@ func (p *provider) vmCreate(
 		diags = f(data, params, diags)
 	}
 
+	diags = handleVMPlacementPolicy(client, data, params, diags)
```
[the remark this answers is not in the document]
Comment (engelmi) [reply internal/ovirt/resource_ovirt_vm.go:221]: Yes and no. The client would be only used by this handle function. I'd prefer passing only used parameters to functions, even if it does break the uniform signature. Can be easily changed, though. What do you think?

[the remark this answers is not in the document]
Comment (janosdebugs) [reply internal/ovirt/resource_ovirt_vm.go:221]: I think it makes for a more readable code on the calling side, and you can always mark the unused parameters with `_` in the function implementation.

File: internal/ovirt/resource_ovirt_vm.go (hunk 1 above)
Comment (janosdebugs) [reply internal/ovirt/resource_ovirt_vm.go:222]: If diags is not empty it should be returned instead of trying to create the VM.

File: internal/ovirt/resource_ovirt_vm.go [hunk 4]
```diff
@@ -377,13 +386,28 @@ func handleVMPlacementPolicy(
...
+
 	if hasPlacementPolicy {
+		isSupported, err := client.SupportsFeature(ovirtclient.FeaturePlacementPolicy)
+		if err != nil {
+			diags = append(diags, errorToDiag("check feature support", err))
+			return diags
+		}
+		if !isSupported {
+			diags = append(diags, diag.Diagnostic{
+				Severity: diag.Error,
```
Comment (janosdebugs) [inline internal/ovirt/resource_ovirt_vm.go:398]: This should be a warning and the placement policy should not be applied.

**Review by janosdebugs — CHANGES_REQUESTED** [review]

**Review by janosdebugs — APPROVED** [review]

File: internal/ovirt/resource_ovirt_vm.go (hunk 4 above)
Comment (engelmi) [reply internal/ovirt/resource_ovirt_vm.go]: True, fixed it.

File: internal/ovirt/resource_ovirt_vm.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (engelmi) [reply internal/ovirt/resource_ovirt_vm.go]: Changed it.
