### PR TITLE
Fix immediate EOF on reads for image transfers via http(s)

### LINKED ISSUE #187: ovirt_image_transfer: The string '' isnt a valid value for the DiskFormat
Hello,
Hoping this is a mistake on my part somewhere, I am trying to add an image via ovirt_image_transfer but I am getting the response stating that the DiskFormat is defaulting to an empty string:

`Error: Fault reason is "Invalid value". Fault detail is "The string '' isn't a valid value for the 'DiskFormat' enumerated type. Valid values are: 'cow', 'raw'.". HTTP response code is "400". HTTP response message is "400 Bad Request".`

HCL for the image transfer:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

create

Terraform will perform the following actions:

ovirt_image_transfer.core_image will be created
resource "ovirt_image_transfer" "c_image" {
alias             = "c_image"
disk_id           = (known after apply)
id                = (known after apply)
source_url        = "http://"
sparse            = true
storage_domain_id = "dfe99181-3902-5d14-bdcd-5ch2237fbe8e"
}
```
I am not used to dealing with go as a language or the structure otherwise i'd have had a poke around myself on how its defined. 

Is there a way of specifying the disk format ?

### PR DESCRIPTION
**Pull request by ipersons**
Fixes #187 

Changes proposed in this pull request:

* Resets file cursor after writing the temp image file for the next read.

Output from acceptance testing:

```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDataCenter_'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_ -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (1.51s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 1.524s
...
```

### CODE REVIEW

File: ovirt/resource_ovirt_image_transfer.go [hunk 1]
```diff
@@ -339,6 +339,13 @@ func PrepareForTransfer(sourceUrl string) (uploadSize int64, qcowSize uint64, so
 
 		sFile, err = ioutil.TempFile("/tmp", "*-ovirt-image.downloaded")
 		io.Copy(sFile, resp.Body)
+
+		// reset cursor to prep for reads
+		_, err = sFile.Seek(0, 0)
+		if err != nil {
+			return 0, 0, nil, "", err
+		}
+
```
Comment (imjoey) [inline ovirt/resource_ovirt_image_transfer.go]: Hi @ipersons , thanks for your great contributions. This indeed is a bug here. IMO, if there could be an additional error checking at https://github.com/oVirt/terraform-provider-ovirt/blob/master/ovirt/resource_ovirt_image_transfer.go#L89 , it will come to be more robust.  What's your insights? Please let me know. Thanks.

Comment (ipersons) [reply ovirt/resource_ovirt_image_transfer.go]: Added some quick error handling to make it more descriptive and to fail prior to the transfer attempt.

Comment (imjoey) [reply ovirt/resource_ovirt_image_transfer.go]: @ipersons Thanks.

**Comment by imjoey** [comment]
LGTM. 
@ipersons , thanks very much for your contributions.
